server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  name: content
  version: 1.1.1

content:
  version: ${info.version}
